# icons.py

CATEGORY_ICONS = {
    "groceries": "mdi:food",
    "rent": "mdi:home",
    "mortgage": "mdi:home",
    "utilities": "mdi:lightning-bolt",
    "electricity": "mdi:lightning-bolt",
    "gas": "mdi:gas-station",
    "fuel": "mdi:gas-station",
    "transport": "mdi:car",
    "car": "mdi:car",
    "public transport": "mdi:bus",
    "entertainment": "mdi:television",
    "fun": "mdi:television",
    "savings": "mdi:piggy-bank",
    "investment": "mdi:piggy-bank",
    "insurance": "mdi:shield-check",
    "phone": "mdi:cellphone",
    "internet": "mdi:cellphone",
    "medical": "mdi:heart-pulse",
    "health": "mdi:heart-pulse",
    "subscriptions": "mdi:credit-card-multiple",
    "streaming": "mdi:credit-card-multiple",
    "education": "mdi:book-open-variant",
    "school": "mdi:book-open-variant",
    "travel": "mdi:airplane",
    "vacation": "mdi:airplane",
    "dining": "mdi:silverware-fork-knife",
    "restaurant": "mdi:silverware-fork-knife",
    "gifts": "mdi:gift",
    "donations": "mdi:gift",
    "clothing": "mdi:tshirt-crew",
    "apparel": "mdi:tshirt-crew",
    "electronics": "mdi:laptop",
    "pets": "mdi:paw",
    "home improvement": "mdi:tools",
    "beauty": "mdi:lipstick",
    "sports": "mdi:soccer",
    "books": "mdi:book",
    "transportation": "mdi:car",
    "childcare": "mdi:baby-bottle",
    "vacations": "mdi:airplane",
    "furniture": "mdi:sofa",
    "toys": "mdi:toys",
    "alcohol": "mdi:beer",
    "fitness": "mdi:run",
    "charity": "mdi:heart",
    "grocery": "mdi:cart",
    "bills": "mdi:cash-multiple",
    "personal care": "mdi:shower",
    "photography": "mdi:camera",
    "music": "mdi:music",
    "shopping": "mdi:shopping",
    "household": "mdi:home-modern",
    "tech": "mdi:smartphone",
    "diy": "mdi:hammer-wrench",
    "garden": "mdi:flower",
    "taxes": "mdi:calculator",
    "loan": "mdi:loan",
    "membership": "mdi:account-group",
    "electronics": "mdi:television",
    "fashion": "mdi:tshirt-crew",
    "office": "mdi:desktop-tower-monitor",
    "food": "mdi:food-apple",
    "transportation": "mdi:train",
    "outdoor": "mdi:snowflake",
    "party": "mdi:balloon",
    "hobbies": "mdi:palette",
    "gifts": "mdi:gift",
    "funds": "mdi:coin",
    "beauty": "mdi:makeup",
    "pets": "mdi:dog",
    "gift shop": "mdi:gift",
    "dental": "mdi:tooth",
    "banking": "mdi:bank",
    "shopping": "mdi:shopping-outline",
    "television": "mdi:television-box",
    "decor": "mdi:sofa",
    "skincare": "mdi:heart-pulse",
    "construction": "mdi:home-city",
    "bookshelf": "mdi:book-open",
    "traveling": "mdi:plane",
    "home repair": "mdi:hammer-wrench",
    "vacation": "mdi:airplane",
    "home office": "mdi:office-building",
    "pets supplies": "mdi:paw",
    "medical expenses": "mdi:heart-pulse",
    "mobile phone": "mdi:cellphone",
    "electricity bill": "mdi:lightning-bolt",
    "cable": "mdi:cable",
    "personal loan": "mdi:loan",
    "savings account": "mdi:bank",
    "student loan": "mdi:school",
    "loan payments": "mdi:loan",
    "gym membership": "mdi:run",
    "insurance payment": "mdi:shield",
    "credit card payment": "mdi:credit-card-check",
    "internet bill": "mdi:cellphone",
    "house maintenance": "mdi:tools",
    "cleaning supplies": "mdi:brush",
    "grocery shopping": "mdi:cart",
    "vehicle expenses": "mdi:car",
    "subscriptions service": "mdi:credit-card-multiple",
    "property tax": "mdi:calculator",
    "home mortgage": "mdi:home",
    "child support": "mdi:baby-bottle",
    "education fees": "mdi:book-open-variant",
    "study materials": "mdi:book"
}

ACCOUNT_ICONS = {
    "checking": "mdi:bank",
    "savings": "mdi:cash-multiple",
    "cash": "mdi:currency-usd",
    "creditcard": "mdi:credit-card",
    "lineofcredit": "mdi:credit-card-plus",
    "otherasset": "mdi:home",
    "otherliability": "mdi:shield-alert",
    "mortgage": "mdi:home-lock",
    "autoloan": "mdi:car",
    "studentloan": "mdi:account-school",
    "personalloan": "mdi:handshake",
    "medicaldebt": "mdi:heart-pulse",
    "otherdebt": "mdi:currency-usd-off",
    "default": "mdi:wallet",
}